packages:
  - packages/*
  - integration_tests
  - website

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild

catalog:
  jsdom: ^27.2.0
  markdown-it: ^14.1.0
  '@types/node': ^24.10.1
  '@types/markdown-it': ^14.1.2
  typescript: ^5.9.3
  tsdown: ^0.16.4
  vitest: ^4.0.12
  bumpp: ^10.3.1
